# Generated by Django 5.0.4 on 2024-05-12 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamWebsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='location',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='location',
            new_name='team',
        ),
    ]
