# Generated by Django 5.0.4 on 2024-05-12 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamWebsite', '0002_rename_location_manager_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamWebsite.team'),
        ),
        migrations.AlterField(
            model_name='member',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamWebsite.team'),
        ),
    ]
