# Generated by Django 5.0.4 on 2024-05-14 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamWebsite', '0003_alter_manager_team_alter_member_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
